# 头部菜单，title: link
menu:
  首页: /
  分类: /categories
  标签: /tags
  归档: /archives  
  关于: /about

# 是否显示目录
TOC: true

# 是否自动播放音乐
autoplay: false

# 默认音乐（随机播放）
mp3: 
    - https://link.hhtjim.com/163/5308028.mp3
    - https://link.hhtjim.com/163/31654479.mp3
    - https://link.hhtjim.com/163/1594220.mp3
    - https://link.hhtjim.com/163/31654455.mp3
    - https://link.hhtjim.com/163/28953875.mp3
# 首页封面图, 为空时取文章的cover作为封面(注意跨域问题,建议使用同源图片)
welcome_cover: /img/background/1.jpg

cover_mode: english
# 默认文章封面图（随机调用,支持外链）
dog_cover: 
  - /img/dog/dog_(1).jpg
  - /img/dog/dog_(2).jpg
  - /img/dog/dog_(3).jpg
  - /img/dog/dog_(4).jpg
  - /img/dog/dog_(5).jpg
  - /img/dog/dog_(6).jpg
  - /img/dog/dog_(7).jpg
  - /img/dog/dog_(8).jpg
  - /img/dog/dog_(9).jpg
  - /img/dog/dog_(10).jpg

english_cover:
  - /img/english/english_(1).jpg
  - /img/english/english_(2).jpg
  - /img/english/english_(3).jpg
  - /img/english/english_(4).jpg
  - /img/english/english_(5).jpg
  - /img/english/english_(6).jpg
  - /img/english/english_(7).jpg
  - /img/english/english_(8).jpg
  - /img/english/english_(9).jpg
  - /img/english/english_(10).jpg
  - /img/english/english_(11).jpg
  - /img/english/english_(12).jpg
  - /img/english/english_(13).jpg
  - /img/english/english_(14).jpg
  - /img/english/english_(15).jpg
  - /img/english/english_(16).jpg
  - /img/english/english_(17).jpg
  - /img/english/english_(18).jpg
  - /img/english/english_(19).jpg
  - /img/english/english_(20).jpg
  - /img/english/english_(21).jpg
  - /img/english/english_(22).jpg
  - /img/english/english_(23).jpg
  - /img/english/english_(24).jpg
  - /img/english/english_(25).jpg
  - /img/english/english_(26).jpg
# 是否使用mathjax
mathjax: false


# 是否关闭默认滚动条
scrollbar: true

# 本地搜索,请将索引文件放在网站根目录,或修改主题js文件的path值
local_search:
    # 是否启用
    enable: true

# 是否显示 一言(hitokoto)
hitokoto: true

# 链接(可选:facebook,twitter,github,wechat,email)
links:
    qq: tencent://message/?uin=2065155193
    zhihu: https://www.zhihu.com/people/jklujklu
    github: https://github.com/jklujklu
    wechat: /img/wechat.png
    email: mailto:jklujklu66@gmail.com
  
# 备案
beian: 
    # 是否显示备案信息
    enable: true
    # 是否在主页面最底下显示备案信息(虽然丑，但是完全满足规定要求)
    enableFooter: false
    # 备案号
    beianInfo: 冀ICP备xxxxxxx号
    # 链接地址
    link: http://www.beian.miit.gov.cn

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否启用评论功能
    enable: false
    # 是否自动展开评论框
    autoExpand: false
    # 应用编号
    clientID: ''
    # 应用秘钥
    clientSecret: ''
    # issue仓库名
    repo: ''
    # Github名
    owner: ''
    # Github名
    admin: ['']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: Fechin

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml
